version: '3.8'

services:
  web:
    build:
      context: https://github.com/kaspaeve/Drudge-Report-Flask.git
    ports:
      - "5000:5000"
    volumes:
      - /portainer/Files/AppData/Config/Drudge:/app  
      - /portainer/Files/AppData/Config/Drudge/data:/app/data  
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
    container_name: Drudge

volumes:
  data_volume:
    external: true
